[versions]
agp = "8.13.0-alpha02"
xposedapi = "82"
ezxhelper = "2.2.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
composeBom = "2025.12.00"
material = "1.13.0"
gson = "2.13.2"
okhttp = "5.3.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
xposedapi = { module = "de.robv.android.xposed:api", version.ref = "xposedapi" }
ezxhelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezxhelper" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

